In [1]:
import pandas as pd
finale_car=pd.read_csv("new_cars.csv")
finale_car.drop(columns="Unnamed: 0",inplace=True)
car_colors=pd.read_csv('Colors.csv',header=None,names=['Color'])

In [2]:
colu=pd.unique(finale_car["Extrior"])

In [3]:
#giving each color a unique number
col=car_colors.Color
Colour={}
colo=col.tolist()
i=0
while i<=len(colo)-1:
    j=colo[i]
    Colour[j]=i
    i=i+1

In [4]:
# giving each brand a unique number
brand=pd.unique(finale_car["Brand"])
brands={}
brand_M=brand.tolist()
i=0
while i<=len(brand_M)-1:
    j=brand_M[i]
    brands[j]=i
    i=i+1

In [5]:
brand_m=list(finale_car["Brand"])

In [6]:
#conversion of brand to numeric  
list_brans = []
i=0
while i<len(brand_m):
    k=brand_m[i]
    numd=brands[k]
    list_brans.append(numd)
    i=i+1   
finale_car["Bran_N"]=list_brans

In [7]:
# checking if a color is in the name if not adds it as other and converts them to factors 
Ext=finale_car.Extrior
list_colu= []
list_col = []
i=0
for Exto in Ext:
    Ex=Exto.lower()
    for Co in col:      
        cole=Co.lower()
        if cole in Ex:
            list_col.append(Co)
            break
    else:
        list_col.append("Others")
while i<len(list_col):
    k=list_col[i]
    numd=Colour[k]
    list_colu.append(numd)
    i=i+1   
finale_car["Color"]=list_col
finale_car["Color_num"]=list_colu

In [28]:
finale_car.to_csv("finale_car.csv",header=True)

In [30]:
type(finale_car["Styles"][0])

str

In [9]:
finale_car.head()

,Vin,Name,Year,Miles,Location,Extrior,Style,Interior,Engine,Transmission,...,Temp,Cylinder,DrivingType,HP_y,Curbwieght_y,RPM,Styles,Brand,Bran_N,Color_num
0,WP1AA2AY4KDA04144,Porsche Cayenne,2019,5885,Norwood MA,Quartzite Metallic,AWD,Black,3.0L V-6 Gas Turbocharged,Automatic,...,V-6 Gas,6,0,340,6239.0,5300.0,SUV,PORSCHE,0,12
1,19XFC2F50GE218876,Honda Civic,2016,43488,Norwood MA,Taffeta White,LX Sedan CVT,Ivory,2.0L Inline-4 Gas,Automatic,...,Inline-4,4,1,158,2751.0,6500.0,Sedan,HONDA,1,0
2,5NPD84LF6HH091405,Hyundai Elantra,2017,26516,Norwood MA,Phantom Black,SE 2.0L Sedan Automatic (alt),Gray,2.0L Inline-4 Gas,Automatic,...,Inline-4,4,1,NaN,NaN,NaN,Sedan,HYUNDAI,2,11
3,1C4BJWEG2FL581541,Jeep Wrangler,2015,56007,Norwood MA,Billet Silver Metallic Clearcoat,Unlimited Sahara,Black,3.6L V-6 Gas,Manual,...,V-6 Gas,6,2,285,4900.0,6400.0,SUV,JEEP,3,10
4,JN8AT2MV0HW005533,Nissan Rogue,2017,28985,Norwood MA,Glacier White,S AWD,Charcoal,2.5L Inline-4 Gas,Automatic,...,Inline-4,4,0,170,4678.0,6000.0,Wagon,NISSAN,4,0